### ISSUE TITLE
regular update

### ISSUE THREAD

**Issue by BuistvoPloti** [openmindculture/intellij-cute-pink-light-theme#97]
Not compatible with the IDE version WebStorm 2022.3

**Comment by openmindculture** [comment]
Thanks @BuistvoPloti , the update is already submitted, and passed automatic compatibility checks, but still pending approval from JetBrains. I already uploaded the update yesterday.

![Screenshot of pending 0.7.0 release](https://user-images.githubusercontent.com/6377941/205045036-9f37de66-a46c-411d-bc98-613fe4232628.png)

**Comment by openmindculture** [comment]
Possible ideas for regular updates before the official releases:

- manual updates and tests
  - schedule work in a calendar, set up a reminder
  - bump version
  - download EAP preview software to test
  - submit to the repository
- automated update
  - develop script / pipeline (manually) to automate the above process
  - use a predefined process, preferably by JetBrains, like dependabot upgrade suggestions
- wildcard compatibility
  - declare compatibility for any upcoming IDEA release
  - JetBrains can display a warning if their compatibility check fails

What I did yesterday was a mixture of manual update and wildcard compatibility. As I failed to get any EAP version to run on my machine last week (both IntelliJ community edition, and WebStorm failed with obscure Java / JDK / JRE / JVM incompatibilities) I finally decided to reset the build version to 2022.2 and claim 2022.3 compatibility anyway, leaving it to the automated compatibility checkers on JetBrains servers. As expected (as this is only a very simple theme), there was no incompatibility! Should have done this when the first EAP versions came out.

**Comment by openmindculture** [comment]
The latest update for 2022.3 has been released.

**Comment by openmindculture** [comment]
Today, I will test and verify a new build that I created bypassing the regular build process.
Assuming that
- my theme is so simple that it will _never_ _ever_ become incompatible
- the upcoming IDEA / PhpStorm / etc. 2023.1 builds will be called 231 internally
I have updated the meta information in META-INF etc. an compressed the `.jar` and `.zip` with appropriate updated filenames. 

Hope that this time there will be an EAP build that runs on my machine without obscure Java library problems, I will verify the first manual theme plugin build. Otherwise I will simply submit it as an update to the JetBrains repository and wait for their verification pipeline to succeed or fail.

**Comment by openmindculture** [comment]
After the [manual build attempt](https://github.com/openmindculture/intellij-cute-pink-light-theme/issues/97#issuecomment-1400007228) failed, I was able to build and verify the updated version with IntelliJ IDEA EAP 2023.1 (ideaIU-231) today. New release: [0.8.0 Compatibility Release for 2023.1 (231)](https://github.com/openmindculture/intellij-cute-pink-light-theme/releases/tag/0.8.0).
Successfully closed #100

**Comment by openmindculture** [comment]
Version 0.8.4 of the Cute Pink Light Theme plugin has been approved by JetBrains and is now publicly available at the following link: https://plugins.jetbrains.com/plugin/16721-cute-pink-light-theme/versions/stable/370932. This version is officially compatible with all upcoming future JetBrains IDEA releases.
